# Generated by Django 5.2.15 on 2026-06-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dataaccess',
            new_name='provenance__convers_3882c0_idx',
            old_name='provenance__convers_8a1b2c_idx',
        ),
    ]
