# Generated by Django 5.2.15 on 2026-06-30 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0003_dataclaim_provenancelink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dataclaim',
            new_name='provenance__convers_4b984f_idx',
            old_name='provenance__convers_claim_idx',
        ),
    ]
