# Generated by Django 5.2.15 on 2026-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentevent',
            name='event_type',
            field=models.CharField(choices=[('token', 'Token'), ('tool_start', 'Tool Start'), ('tool_end', 'Tool End'), ('plan', 'Plan'), ('table', 'Table'), ('chart', 'Chart'), ('file_created', 'File Created'), ('file_updated', 'File Updated'), ('error', 'Error'), ('done', 'Done')], max_length=20),
        ),
    ]
