import React, { useState } from "react";
import { Icon } from "../../components/icons/Icon.jsx";
import { REGION_ROWS, SHEET_HEADER, SHEET_ROWS } from "./data.js";

/** Clickable file card shown inside an agent message. */
export function FileCard({ f, active, onOpen }) {
  const [h, setH] = useState(false);
  const sheet = f.kind === "sheet";
  return (
    <button onClick={() => onOpen(f)} onMouseEnter={() => setH(true)} onMouseLeave={() => setH(false)}
      style={{ display: "flex", alignItems: "center", gap: 12, width: "100%", maxWidth: 380, textAlign: "left", cursor: "pointer",
        padding: "11px 12px", borderRadius: "var(--ay-radius-md)", fontFamily: "inherit",
        border: `1px solid ${active ? "var(--ay-ink)" : "var(--ay-border-strong)"}`,
        background: active ? "var(--ay-bg-subtle)" : h ? "var(--ay-surface-hover)" : "var(--ay-surface)",
        boxShadow: active ? "none" : "var(--ay-shadow-xs)", transition: "background .12s,border-color .12s" }}>
      <span style={{ width: 38, height: 38, borderRadius: "var(--ay-radius-md)", flex: "none", display: "inline-flex", alignItems: "center",
        justifyContent: "center", background: sheet ? "var(--ay-success-50)" : "var(--ay-blue-50)",
        color: sheet ? "var(--ay-success-700)" : "var(--ay-blue-700)" }}>
        <Icon name={sheet ? "sheet" : "filetext"} size={19} />
      </span>
      <span style={{ minWidth: 0, flex: 1 }}>
        <span style={{ display: "block", fontSize: 14, fontWeight: 600, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{f.name}</span>
        <span style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "var(--ay-text-subtle)", marginTop: 1 }}>
          <span style={{ fontFamily: "var(--ay-font-mono)", fontWeight: 500, letterSpacing: "0.02em" }}>{f.ext}</span>· {f.meta.split("· ")[1]}
        </span>
      </span>
      <span style={{ flex: "none", color: "var(--ay-text-subtle)" }}><Icon name="chevright" size={16} /></span>
    </button>
  );
}

function PanelBtn({ icon, onClick, title }) {
  const [h, setH] = useState(false);
  return (
    <button onClick={onClick} title={title} onMouseEnter={() => setH(true)} onMouseLeave={() => setH(false)}
      style={{ width: 32, height: 32, display: "inline-flex", alignItems: "center", justifyContent: "center", border: "none",
        borderRadius: "var(--ay-radius-sm)", background: h ? "var(--ay-surface-hover)" : "transparent", color: "var(--ay-text-muted)", cursor: "pointer" }}>
      <Icon name={icon} size={16} />
    </button>
  );
}

function DocView() {
  const h2 = { fontSize: 17, fontWeight: 600, letterSpacing: "-0.01em", margin: "28px 0 8px" };
  const p = { fontSize: 14.5, lineHeight: 1.7, color: "var(--ay-text)", margin: "0 0 8px" };
  const li = { fontSize: 14.5, lineHeight: 1.6, marginBottom: 6 };
  return (
    <div style={{ flex: 1, overflowY: "auto", padding: "28px 0 56px" }}>
      <div style={{ width: "100%", maxWidth: 640, margin: "0 auto", background: "var(--ay-surface)", border: "1px solid var(--ay-border)",
        borderRadius: "var(--ay-radius-md)", boxShadow: "var(--ay-shadow-sm)", padding: "48px 54px" }}>
        <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: "0.07em", textTransform: "uppercase", color: "var(--ay-blue-600)" }}>Quarterly report</div>
        <h1 style={{ fontSize: 30, fontWeight: 700, letterSpacing: "-0.025em", margin: "8px 0 6px", lineHeight: 1.12 }}>Q2 Revenue Report</h1>
        <div style={{ fontSize: 13, color: "var(--ay-text-subtle)", paddingBottom: 22, marginBottom: 4, borderBottom: "1px solid var(--ay-border)" }}>
          Generated by Ayron · June 15, 2026 · Acme Analytics</div>
        <h2 style={h2}>Summary</h2>
        <p style={p}>Q2 closed at <strong>$1.28M</strong> in revenue, up <strong>12.4%</strong> versus Q1 and the strongest quarter on record. Growth was broad-based but led by EMEA and APAC, while LATAM softened slightly on FX headwinds.</p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 10, margin: "18px 0 6px" }}>
          {[["Total revenue", "$1.28M", "+12.4%"], ["Orders", "15,209", "+8.1%"], ["Avg. order value", "$84.48", "+2.3%"]].map((k, i) => (
            <div key={i} style={{ border: "1px solid var(--ay-border)", borderRadius: "var(--ay-radius-md)", padding: "12px 14px" }}>
              <div style={{ fontSize: 12, color: "var(--ay-text-muted)" }}>{k[0]}</div>
              <div style={{ fontFamily: "var(--ay-font-mono)", fontSize: 19, fontWeight: 600, marginTop: 3 }}>{k[1]}</div>
              <div style={{ fontSize: 12, fontWeight: 500, color: "var(--ay-success-700)", marginTop: 2 }}>▲ {k[2]}</div>
            </div>
          ))}
        </div>
        <h2 style={h2}>Revenue by region</h2>
        <div style={{ border: "1px solid var(--ay-border)", borderRadius: "var(--ay-radius-md)", overflow: "hidden", margin: "4px 0" }}>
          {REGION_ROWS.map((r, i) => (
            <div key={r.r} style={{ display: "flex", padding: "10px 14px", fontSize: 14, borderTop: i ? "1px solid var(--ay-border-subtle)" : "none" }}>
              <span style={{ flex: 1, fontWeight: 500 }}>{r.r}</span>
              <span style={{ fontFamily: "var(--ay-font-mono)", fontSize: 13, marginRight: 14 }}>{r.v}</span>
              <span style={{ width: 56, textAlign: "right", fontSize: 13, fontWeight: 500, color: r.up ? "var(--ay-success-700)" : "var(--ay-danger-700)" }}>{r.d}</span>
            </div>
          ))}
        </div>
        <h2 style={h2}>Highlights</h2>
        <ul style={{ margin: "0 0 4px", paddingLeft: 20, color: "var(--ay-text)" }}>
          <li style={li}>EMEA grew <strong>+18.2%</strong>, contributing 38% of total revenue.</li>
          <li style={li}>APAC was the fastest-growing region at <strong>+22.7%</strong>, driven by new Enterprise logos.</li>
          <li style={li}>Enterprise plan revenue rose <strong>+31%</strong> QoQ, now 15% of the book.</li>
        </ul>
        <h2 style={h2}>Recommended actions</h2>
        <ul style={{ margin: 0, paddingLeft: 20, color: "var(--ay-text)" }}>
          <li style={li}>Reallocate marketing spend toward APAC to compound momentum.</li>
          <li style={li}>Investigate LATAM softness — likely FX, confirm against Stripe settlement data.</li>
          <li style={li}>Set a weekly automated digest so this view stays current for the team.</li>
        </ul>
      </div>
    </div>
  );
}

function SheetView() {
  const cols = ["A", "B", "C", "D", "E"];
  const GT = "38px 158px repeat(4,1fr)";
  const cellBase = { padding: "7px 10px", fontSize: 13, borderRight: "1px solid var(--ay-border-subtle)",
    borderBottom: "1px solid var(--ay-border-subtle)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" };
  const hdrCell = { ...cellBase, background: "var(--ay-neutral-100)", color: "var(--ay-text-subtle)", fontFamily: "var(--ay-font-mono)",
    fontSize: 11, fontWeight: 500, textAlign: "center", display: "flex", alignItems: "center", justifyContent: "center" };
  return (
    <div style={{ flex: 1, minHeight: 0, display: "flex", flexDirection: "column", background: "var(--ay-surface)" }}>
      <div style={{ flex: "none", display: "flex", alignItems: "center", height: 34, borderBottom: "1px solid var(--ay-border)", background: "var(--ay-bg)" }}>
        <div style={{ width: 62, textAlign: "center", fontFamily: "var(--ay-font-mono)", fontSize: 12, color: "var(--ay-text-muted)", borderRight: "1px solid var(--ay-border)", lineHeight: "34px" }}>B2</div>
        <div style={{ padding: "0 6px", color: "var(--ay-text-subtle)", fontStyle: "italic", fontSize: 12, borderRight: "1px solid var(--ay-border)", lineHeight: "34px" }}>fx</div>
        <div style={{ padding: "0 12px", fontFamily: "var(--ay-font-mono)", fontSize: 12.5, color: "var(--ay-text)" }}>486200</div>
      </div>
      <div style={{ flex: 1, overflow: "auto" }}>
        <div style={{ display: "grid", gridTemplateColumns: GT, minWidth: 540, borderTop: "1px solid var(--ay-border-subtle)", borderLeft: "1px solid var(--ay-border-subtle)" }}>
          <div style={hdrCell}></div>
          {cols.map((c) => <div key={c} style={hdrCell}>{c}</div>)}
          <div style={hdrCell}>1</div>
          {SHEET_HEADER.map((c, j) => <div key={j} style={{ ...cellBase, fontWeight: 600, textAlign: j === 0 ? "left" : "right", background: "var(--ay-bg-subtle)" }}>{c}</div>)}
          {SHEET_ROWS.map((row, ri) => {
            const total = ri === SHEET_ROWS.length - 1;
            return (
              <React.Fragment key={ri}>
                <div style={hdrCell}>{ri + 2}</div>
                {row.map((cell, ci) => {
                  const sel = ri === 0 && ci === 1;
                  const neg = ci === 4 && cell.startsWith("-");
                  return (
                    <div key={ci} style={{ ...cellBase, textAlign: ci === 0 ? "left" : "right",
                      fontFamily: ci === 0 ? "var(--ay-font-sans)" : "var(--ay-font-mono)",
                      fontWeight: total ? 600 : ci === 4 ? 500 : 400,
                      color: ci === 4 ? (neg ? "var(--ay-danger-700)" : "var(--ay-success-700)") : "var(--ay-text)",
                      background: total ? "var(--ay-bg-subtle)" : "var(--ay-surface)",
                      boxShadow: sel ? "inset 0 0 0 2px var(--ay-accent)" : "none" }}>{cell}</div>
                  );
                })}
              </React.Fragment>
            );
          })}
        </div>
      </div>
      <div style={{ flex: "none", display: "flex", alignItems: "center", height: 34, borderTop: "1px solid var(--ay-border)", background: "var(--ay-bg-subtle)", padding: "0 8px", gap: 2 }}>
        <span style={{ height: 24, padding: "0 12px", display: "inline-flex", alignItems: "center", fontSize: 12.5, fontWeight: 600, background: "var(--ay-surface)", border: "1px solid var(--ay-border)", borderRadius: "var(--ay-radius-sm)" }}>Revenue</span>
        <span style={{ width: 24, height: 24, display: "inline-flex", alignItems: "center", justifyContent: "center", color: "var(--ay-text-subtle)", cursor: "pointer" }}><Icon name="plus" size={14} /></span>
      </div>
    </div>
  );
}

/**
 * Right-side artifact viewer — renders an agent-generated document or
 * spreadsheet in a split pane, with copy / download / expand / close.
 */
export function ArtifactPanel({ doc, expanded, onToggleExpand, onClose }) {
  const sheet = doc.kind === "sheet";
  return (
    <div style={{ flex: expanded ? 1 : "0 0 520px", maxWidth: expanded ? "none" : "52%", minWidth: 0, borderLeft: "1px solid var(--ay-border)",
      display: "flex", flexDirection: "column", height: "100%", background: "var(--ay-bg-subtle)" }}>
      <div style={{ flex: "none", height: 56, display: "flex", alignItems: "center", gap: 12, padding: "0 14px 0 16px", borderBottom: "1px solid var(--ay-border)", background: "var(--ay-bg)" }}>
        <span style={{ width: 32, height: 32, borderRadius: 8, flex: "none", display: "inline-flex", alignItems: "center", justifyContent: "center",
          background: sheet ? "var(--ay-success-50)" : "var(--ay-blue-50)", color: sheet ? "var(--ay-success-700)" : "var(--ay-blue-700)" }}>
          <Icon name={sheet ? "sheet" : "filetext"} size={17} />
        </span>
        <div style={{ minWidth: 0 }}>
          <div style={{ fontSize: 14, fontWeight: 600, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{doc.name}</div>
          <div style={{ fontSize: 11.5, color: "var(--ay-text-subtle)" }}><span style={{ fontFamily: "var(--ay-font-mono)" }}>{doc.ext}</span> · {doc.meta.split("· ")[1]}</div>
        </div>
        <span style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 2 }}>
          <PanelBtn icon="copy" title="Copy" />
          <PanelBtn icon="download" title="Download" />
          <span style={{ width: 1, height: 20, background: "var(--ay-border)", margin: "0 4px" }} />
          <PanelBtn icon="expand" title={expanded ? "Collapse" : "Expand"} onClick={onToggleExpand} />
          <PanelBtn icon="close" title="Close" onClick={onClose} />
        </span>
      </div>
      {sheet ? <SheetView /> : <DocView />}
    </div>
  );
}
